"""Add weather column to record table

Revision ID: 62e12263d4cb
Revises: 7a10f09b2626
Create Date: 2020-04-19 10:07:28.252279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e12263d4cb'
down_revision = '7a10f09b2626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('weather', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'weather')
    # ### end Alembic commands ###
